# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ('-date',), 'verbose_name': 'Diary entry', 'verbose_name_plural': 'Diary entries'},
        ),
    ]
