# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 12:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'font': 'Caveat', 'theme': 'light'}, null=True, verbose_name='settings'),
        ),
    ]
